# Generated by Django 3.0.4 on 2022-02-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=524)),
                ('images', models.FileField(upload_to='pattern_uploads/')),
            ],
        ),
    ]
